name: Full Stack Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 安装 Node.js 和 npm
    - name: Install Node.js and npm
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '14'

    # 安装 vte 和其他前端依赖
    - name: Install frontend dependencies
      working-directory: ./client
      run: |
        npm install vite -g
        npm install
      env:
        NODE_ENV: production

    # 前端构建步骤
    - name: Build Vue App
      working-directory: ./client
      run: |
        npm run build
      env:
        NODE_ENV: production

    # 缓存前端构建依赖
    - name: Cache frontend dependencies
      uses: actions/cache@v2
      with:
        path: client/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('client/package-lock.json') }}

    # 复制前端构建结果到后端的public目录
    - name: Copy frontend build output to server
      run: cp -r ./client/dist ./server/public

    # 后端构建步骤
    - name: Build and start Node.js server
      working-directory: ./server
      run: |
        npm install
        node app.js
      env:
        NODE_ENV: production

    # 缓存后端构建依赖
    - name: Cache backend dependencies
      uses: actions/cache@v2
      with:
        path: server/node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('server/package-lock.json') }}
